apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-ghost
  namespace: poc
  labels:
    app: ghost
    tier: web
    env: poc
spec:
  # managed with HPA
  # replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
        tier: web
        env: poc
    spec:
      containers:
        - name: ghost
          image: ghost:4.24.0
          ports:
            - containerPort: 2368
          env:
            - name: GHOST_INSTALL
              valueFrom:
                configMapKeyRef:
                  name: ghost-config
                  key: ghost_install
            - name: GHOST_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: ghost-config
                  key: ghost_content
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ghost-config
                  key: node_env
