apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-ghost
  namespace: poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-ghost
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
