apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: poc
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.poc.svc.cluster.local
    path: "/"
  mountOptions:
    - nfsvers=4.2
